# Generated by Django 2.2 on 2019-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20190410_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyBudget',
            new_name='SalesTarget',
        ),
        migrations.RemoveConstraint(
            model_name='salestarget',
            name='check_valid_month',
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.CheckConstraint(check=models.Q(month__in=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)), name='check_valid_month'),
        ),
    ]
